# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18oPcYZKnfyvu0zH4EALruqlo9ZNeR2_t
"""

def sentence_operations(sentence1, sentence2):
  set1 = set(sentence1.lower().split())
  set2 = set(sentence2.lower().split())

  intersection = set1.intersection(set2)
  union = set1.union(set2)

  return intersection, union

file1 = "this is sample text about legal sample issues"
file2 = "This text legal discusses legal and ethical this issues in legal computing"
intersection, union = sentence_operations(file1, file2)
print("similarity:", intersection)
print("Union:", union)